function J = costFunction(z, mpc)
[X, U] = getDecisions(z, mpc);
X = X'; U = U';
cost = sum(diag((X(:,1:end-1)-mpc.x_d(:,mpc.current:mpc.current + mpc.predictionHorizon-2))'*mpc.Q ...
    *(X(:,1:end-1)-mpc.x_d(:,mpc.current:mpc.current + mpc.predictionHorizon-2)))) ...
      + sum(diag(U'*mpc.P*U));
J = cost + ...
    (X(:,end) - mpc.x_d(:,mpc.current + mpc.predictionHorizon - 1))' * mpc.Qn * (X(:,end) - mpc.x_d(:,mpc.current + mpc.predictionHorizon - 1));
end